# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a79de94565d1e25d87d4c7f6423b1182ae66e1c1757ae3bb1867e90888fe5fcc99fc25b163f4acd1c550f3549eb2b67e9f91df57c687d54bf2e87bf49e231ed1

test:
  secret_key_base: 29b66b165d338c7493fec64fe730b9a9de4e2e810e95dc1dbb2b4e2c3ad96ca88f61f72b75e2595606bc0b7b3d261e9a86d943282b18df2970434a2f77fa9fd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
